Create TABLE "DAP_Project"."Electric_Vehicles".EV_Registration (
    Clean_Alternative_Fuel_Vehicle_Type VARCHAR(255),
    VIN VARCHAR(10),
    DOL_Vehicle_ID VARCHAR(255),
    Model_Year INT,
    Make VARCHAR(255),
    Model VARCHAR(255),
    Vehicle_Primary_Use VARCHAR(255),
    Electric_Range INT,
    Odometer_Reading INT,
    Odometer_Code VARCHAR(255),
    New_or_Used_Vehicle VARCHAR(255),
    Sale_Price FLOAT,
    Sale_Date DATE,
    Base_MSRP FLOAT,
    Transaction_Type VARCHAR(255),
    DOL_Transaction_Date DATE,
    Transaction_Year INT,
    County VARCHAR(255),
    City VARCHAR(255),
    State_of_Residence VARCHAR(255),
    Postal_Code VARCHAR(255),
    HB_2778_Exemption_Eligibility VARCHAR(255),
    HB_2042_Clean_Alternative_Fuel_Vehicle_Eligibility VARCHAR(255),
    Meets_2019_HB_2042_Electric_Range_Requirement VARCHAR(255),
    Meets_2019_HB_2042_Sale_Date_Requirement VARCHAR(255),
    Meets_2019_HB_2042_Sale_Price_Value_Requirement VARCHAR(255),
    HB_2042_Battery_Range_Requirement VARCHAR(255),
    HB_2042_Purchase_Date_Requirement VARCHAR(255),
    HB_2042_Sale_Price_Value_Requirement VARCHAR(255),
    Electric_Vehicle_Fee_Paid VARCHAR(255),
    Transportation_Electrification_Fee_Paid VARCHAR(255),
    Hybrid_Vehicle_Electrification_Fee_Paid VARCHAR(255),
    Census_Tract_2020 VARCHAR(255),
    Legislative_District VARCHAR(255),
    Electric_Utility VARCHAR(255)
);

create table "DAP_Project"."Electric_Vehicles".ev_registration_fin AS
SELECT 
vin, 
clean_alternative_fuel_vehicle_type, 
dol_vehicle_id, model_year, make, model, 
vehicle_primary_use, electric_range, 
odometer_reading, odometer_code, 
new_or_used_vehicle, sale_price, 
sale_date, base_msrp, 
transaction_type, 
dol_transaction_date, 
transaction_year, county, city, state_of_residence, 
postal_code, hb_2778_exemption_eligibility, 
hb_2042_clean_alternative_fuel_vehicle_eligibility, 
meets_2019_hb_2042_electric_range_requirement, 
meets_2019_hb_2042_sale_date_requirement, 
meets_2019_hb_2042_sale_price_value_requirement, 
hb_2042_battery_range_requirement, 
hb_2042_purchase_date_requirement, 
hb_2042_sale_price_value_requirement, electric_vehicle_fee_paid, 
transportation_electrification_fee_paid, 
hybrid_vehicle_electrification_fee_paid, 
electric_utility
FROM "DAP_Project"."Electric_Vehicles".ev_registration
where 1=2;
